export const MAX_INPUT_LENGTH = 300;
export const MAX_OUTPUT_LENGTH = 500;

export const RATE_LIMIT_MAX_PER_MINUTE = 10;
export const RATE_LIMIT_WINDOW_MS = 60_000;
export const RATE_LIMIT_REPEAT_INPUT_THRESHOLD = 5;
export const RATE_LIMIT_PENALTY_MS = 120_000;
